### ISSUE TITLE
Where we are going

### ISSUE THREAD

**Issue by MaxKostiv** [MaxKostiv/hello-world#3]

**Comment by voloshka19** [comment]
ohh, I wanna go to Thailand

**Comment by MaxKostiv** [comment]
I think Egypt is also good place to spend your vacation

**Comment by voloshka19** [comment]
Yes, but it was my childhood dream to go to Thailand

**Comment by MaxKostiv** [comment]
ok then , let's make your dream true

**Comment by voloshka19** [comment]
=)

**Comment by MaxKostiv** [comment]
done
