### ISSUE TITLE
Hotel

### ISSUE THREAD

**Issue by MaxKostiv** [MaxKostiv/hello-world#5]

**Comment by MaxKostiv** [comment]
I think hotel BelAire is a good idea

**Comment by voloshka19** [comment]
ohh noo, I recommend you to live in Hotel Muse Bangkok Langsuan

**Comment by MaxKostiv** [comment]
But it is very expensive

**Comment by voloshka19** [comment]
I don't care)

**Comment by MaxKostiv** [comment]
ohhh, ok
